### ISSUE TITLE
I get a random crash

### ISSUE THREAD

**Issue by xiejiangzhi** [typhoeus/ethon#147] opened 2018-03-20 06:04 UTC
```
/home/jenkins/.rvm/gems/ruby-2.2.5/gems/ethon-0.11.0/lib/ethon/easy/operations.rb:29: [BUG] Segmentation fault at 0x00000000000050
ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0188 p:---- s:1077 e:001076 CFUNC  :easy_perform
c:0187 p:0016 s:1073 e:001072 METHOD /home/jenkins/.rvm/gems/ruby-2.2.5/gems/ethon-0.11.0/lib/ethon/easy/operations.rb:29
c:0186 p:0024 s:1070 e:001069 METHOD /home/jenkins/.rvm/gems/ruby-2.2.5/gems/typhoeus-1.3.0/lib/typhoeus/request/operations.rb:16
c:0185 p:0052 s:1066 e:001065 METHOD /home/jenkins/.rvm/gems/ruby-2.2.5/gems/typhoeus-1.3.0/lib/typhoeus/request/cacheable.rb:18
c:0184 p:0036 s:1062 e:001061 METHOD /home/jenkins/.rvm/gems/ruby-2.2.5/gems/typhoeus-1.3.0/lib/typhoeus/request/block_connection.rb:31
c:0183 p:0050 s:1059 e:001058 METHOD /home/jenkins/.rvm/gems/ruby-2.2.5/gems/typhoeus-1.3.0/lib/typhoeus/request/stubbable.rb:25
c:0182 p:0022 s:1055 e:001054 METHOD /home/jenkins/.rvm/gems/ruby-2.2.5/gems/typhoeus-1.3.0/lib/typhoeus/request/before.rb:26
c:0181 p:0037 s:1052 e:001051 METHOD /home/jenkins/.rvm/gems/ruby-2.2.5/gems/typhoeus-1.3.0/lib/typhoeus/adapters/faraday.rb:82
```

My ruby process was killed.

**Comment by Flipez** [comment] 2018-03-27 07:44
Same for me.

Any ideas what could cause this?

**Comment by xiejiangzhi** [comment] 2018-03-27 10:57
I already removed it, haha

Robert Müller <notifications@github.com> 于 2018年3月27日周二 15:44写道：

**Comment by Kjarrigan** [comment] 2021-02-09 12:41
Closing this due to not being updated for years. If you get that error again please provide a small script to reproduce the issue and I'll reopen it.

**Closed by Kjarrigan** 2021-02-09 12:41 UTC
